name: Main Branch Pipeline
on:
  push:
    branches:
      - main
jobs:
  test:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      run_tests: true
  
  docker:
    needs: test
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image_name: devops-practice-api
      tag: sha-${{ github.sha }}
    secrets:
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_token: ${{ secrets.DOCKERHUB_TOKEN }}

  vulnerabilityTEST:
    steps:
      - name: Scan Docker Image for Vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'your-username/your-app:latest'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Mock Deployment
        run: echo "Deploying image ${{ needs.docker.outputs.image_url }} to production"